### ISSUE TITLE
is this project live, any plans for Sublime Text 3?

### ISSUE THREAD

**Issue by aftabnaveed** [zookatron/sublime-collaboration#12]
is this project live, any plans for Sublime Text 3?

**Comment by benlake** [comment]
Not that I've seen. I've used floobits.com as of late. Really good Sublime integration.

**Comment by zookatron** [comment]
Hey, sorry, I haven't had time to update this for a while, and I still haven't upgraded to Sublime Text 3 actually, since I didn't want to pay again for an upgrade that didn't really add anything I was interested in. I am hoping to get a chance to release a version that is compatible with ST3 at some point though.

**Comment by AmazingGamerBoy** [comment]
Come on guys, its been 3-4 years now. Please get this plugin sublime 3 compatible. if you cannot, are there any free collaboration plugins out there for sublime 3 like this one? Floobits isn't good because you have to pay to make it private.

**Comment by arjamizo** [comment]
@AmazingGamerBoy look for Rudel (for emacs) or anything that implements `obby` protocol
https://www.emacswiki.org/emacs/CollaborativeEditing 
or technomacy/conspire

**Comment by zookatron** [comment]
Sublime Collaboration should now support the new Sublime Text 3 API. (Tested with Sublime Text build 3114) Please let me know if you find any bugs with the new version.
