### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by iamtiantian** [zookatron/sublime-collaboration#14]
In my PC ONE, everything is ok. I toggle a **local server** and connect to _localhost_. But in my PC TWO, I can't connect to this _localhost_ _(always 'Client error: could not connect to server')_ unless I toggle a new **local server**, but then there are 2 local servers so these two PCs can't co-work .

What should I do?
Thanks a lot!

**Comment by zookatron** [comment]
Hi @iamtiantian,

What you need to enter instead of localhost is your local or external IP address. If you're connecting over a LAN, then you need your local IP, if you're connecting over the internet you need your external IP. You can learn more about this concept more [here](http://lifehacker.com/5833108/how-to-find-your-local-and-external-ip-address).
